apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-replicaset
  namespace: webapp
  labels:
    app: employees
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
      version: v1
  template:
    metadata:
      labels:
        app: employees
        version: v1
    spec:
      containers:
      - name: webapp
        image: 810910366372.dkr.ecr.us-east-1.amazonaws.com/fatima-assignment-2:webapp
        ports:
        - containerPort: 8080
        env:
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: db-config
              key: DBUSER
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: db-config
              key: DBPWD
        - name: DATABASE
          valueFrom:
            secretKeyRef:
              name: db-config
              key: DATABASE
        - name: DBHOST
          valueFrom:
            secretKeyRef:
              name: db-config
              key: DBHOST
        - name: DBPORT
          value: "3306"
